### ISSUE TITLE
Hii, i need your help, please

### ISSUE THREAD

**Issue by hirios** [jmctune/dqxclarity#115]
I'm very new to memory editing and game hacking.

I wanted to replicate this search using python. How do I do that?
![Snap 2021-09-06 at 13 34 03](https://user-images.githubusercontent.com/35049559/132245324-b999f07e-634e-4c34-9103-188aa0e8a931.png)

So I took a code from you and I did it
```
import pymem

indexPattern = bytes.fromhex("3C 8F 37 80") #Apparently this is the hex corresponding to the number 1016018816

def process_scan(handle: int, pattern: bytes, end_address: int = 0x7fffffff):
  next_region = 0
  while next_region < end_address:
    next_region, found = pymem.pattern.scan_pattern_page(handle, next_region, pattern)
    if found:
      print(hex(found))

  return found

pm = pymem.Pymem('HD-Player.exe')
handle = pm.process_handle

process_scan(handle, indexPattern)
```

But nothing is returned to me. I'm trying to create a bluestack android emulator hack pro

**Comment by jmctune** [comment]
Hey there,

I'm unsure what type of data `1016018816` is (string, int, etc) as well as the encoding of the data, but the hex for that value would be `31 30 31 36 30 31 38 38 31 36` (assuming UTF-8, which is pretty common). To replicate this search in Cheat Engine, you'd want to change your scan type to "Array of Byte", check the "Hex" box and enter your hex string.

You can use an online tool like https://onlineutf8tools.com/convert-utf8-to-hexadecimal for a quick check to convert that value to the appropriate hexadecimal value for several encoding types.

I believe that function you posted doesn't return all matching values for that pattern scan. This was introduced somewhat recently in `pymem` in commit https://github.com/srounet/Pymem/commit/d29f9f2990953a1adaff8f5bb47e4d4af4539506. You'll want to rewrite your function to support `return_multiple` so you get all matches.

The way my program does it is altered slightly as I manage my own fork of the module for the purpose of getting it to work with the game I'm touching.

Hope this helps.
